robot.name=Circler
robot.classname=spar.Circler
robot.description=Bot de treino - arquetipo de adversario. Nao e o robo de competicao.
robot.author.name=Equipe Leviathan
robocode.version=1.11.1
robot.java.source.included=false
