robot.name=TCN
robot.classname=tcn.TCN
robot.description=Sobrevivencia primeiro em melee, agressao total em duelo.\
 Campo de risco, canhao estatistico GuessFactor, wave surfing e interceptacao de projeteis.
robot.author.name=Equipe TCN
robot.webpage=
robocode.version=1.11.1
robot.java.source.included=false
