robot.name=T67
robot.classname=teste.T67
robot.description=Robo competidor real, publicado em github.com/thales-biondi12/Robocode. Copia literal, para teste. Nao e nosso codigo.
robot.author.name=thales-biondi12
robocode.version=1.11.1
robot.java.source.included=false
